name: 02 - workflow events

on: workflow_dispatch

jobs:
    echo:
        runs-on: ubunto-latest
        steps:
            - name: show the trigger
              run: echo "ive been triggered by a(n) ${{ github.event_name }}"