# dar uma olhadinha melhor na prática dessa aula e fazer a parte dois 'activities' aqui
name: 05 - 1 - filters - activity - types

on: 
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main

jobs:
    echo:
        runs-on: ubunto-latest
        steps:
            - run: echo "running whenever a PR is opened or synchronized AND base branch is main"