name: 07 - using expression
run-name: 07 - using expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

on: 
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] print start-up'
              if: ${{inputs.debug}}
              run: |
                echo "triggered by: ${{github.event_name}}"
                echo "Branch: ${{github.ref}}"
                echo "Commit SHA: ${{github.sha}}"
                echo "Runner OS: ${{runner.os}}"
            - name: '[debug] Print when triggered from main'
              if: ${{inputs.debug && github.ref == 'refs/heads/main'}}
              run: echo "I was trigged from main"
            - name: Greeting
              run: echo "Hello World"
