name: 10 - Controlling the Execution Flow

on:
    workflow_dispatch:
        inputs:
            pass-unit-tests:
                type: boolean
                description: whether unit tests will pass or not
                default: true

jobs:
    lint-buid:
        runs-on: ubuntu-latest
        steps:
            - name: Lint and build
              run: |
                echo "Linting and building project"
        continue-on-error: true
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Running unit tests
              run: |
                echo "Running tests.."
            - name: Failing tests
              if: ${{ !inputs.pass-unit-tests }}
              run: exit 1
    deploy-nonprod:
        runs-on: ubuntu-latest
        needs: 
            - lint-buid
            - unit-test
        steps:
            - name: Deplying to nonprod
              run: echo "Deplying to nonprod"
    e2e-test:
        runs-on: ubuntu-latest
        needs:
            - deploy-nonprod
        steps:
            - name: Running E2E tests
              run: echo "Running E2E tests"
    load-test:
        runs-on: ubuntu-latest
        needs:
            - deploy-nonprod
        steps:
            - name: Running LOAD tests
              run: echo "Running LOAD tests"
    deploy-prod:
        runs-on: ubuntu-latest
        needs:
            - load-test
            - e2e-test
        steps:
            - name: Deplying to prod
              run: echo "Deplying to prod"
